/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlabs;

import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public final class AboutAd extends javax.swing.JFrame {

    /**
     * Creates new form AboutAd
     */
    
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    
    public void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }
    
     // username, userid
    public static String info[] = new String[100];
    public String debug(int l){
        String s = "";
        for( int i = 0; i < l; i++ ){
            s += info[i];
            s += "\n";
        }
        return s;
    }
    
    public AboutAd() throws SQLException {
        initComponents();
        
        LogOut1.setText(info[0]);
        int id = Integer.parseInt(info[2]);
        make_connection();
        String q = "SELECT * FROM ActiveAds WHERE ID = ?";
        pst = (PreparedStatement) con.prepareStatement(q);
        pst.setInt(1, id);
        rs = pst.executeQuery();  
        while( rs.next() ){
            String text = rs.getString(1);
            if( "Call Goal".equals(text) ){
                text = "Call your business";
            }
            else{
                text = "Take an action on your website";
            }
            goal.setText(text);
            area.setText(rs.getString(2));
            product.setText(rs.getString(4));
            headline.setText(rs.getString(5));
            URL.setText(rs.getString(7));
            desc.setText(rs.getString(6));
            Date d = new Date(rs.getDate(11).getTime());
            date.setText(d.toString());
            d = new Date(rs.getDate(12).getTime());
            date1.setText(d.toString());
            byte[] Img = rs.getBytes("Image");
            ImageIcon image = new ImageIcon(Img);
            Image im =  image.getImage();
            Image myImg = im.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newImage = new ImageIcon(myImg);
            img.setIcon(newImage);
            Img = rs.getBytes("Logo");
            image = new ImageIcon(Img);
            im =  image.getImage();
            myImg = im.getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
            newImage = new ImageIcon(myImg);
            logo.setIcon(newImage);
            q = "SELECT * FROM EmailID WHERE AdsId = ?";
            pst = (PreparedStatement) con.prepareStatement(q);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            if( rs.next() ){
                current_id.setText("ID : " +id+ " ( Active )");
            }
            else{
                current_id.setText("ID : " +id+ " ( Stopped )");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Home2 = new javax.swing.JButton();
        headline = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        URL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        goal = new javax.swing.JLabel();
        area = new javax.swing.JLabel();
        product = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        preview = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        privacy1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        LogOut1 = new javax.swing.JButton();
        current_id = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Ad");

        jLabel13.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Labs");

        Home2.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.57.11 PM.png")); // NOI18N
        Home2.setBorderPainted(false);
        Home2.setContentAreaFilled(false);
        Home2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Home2)
                .addGap(1, 1, 1)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 819, -1));

        headline.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        headline.setForeground(new java.awt.Color(153, 153, 255));
        headline.setText("Headline1 | Headline2");
        jPanel2.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 390, 30));

        desc.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 153, 153));
        desc.setText("Description");
        jPanel2.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 380, 30));

        date1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        date1.setForeground(new java.awt.Color(0, 204, 102));
        date1.setText("2018-9-2");
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 130, 30));

        date.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 204, 102));
        date.setText("2-9-2018");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 130, 30));

        URL.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        URL.setForeground(new java.awt.Color(122, 191, 130));
        URL.setText("website URL");
        jPanel2.add(URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 350, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.51.57 AM.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.55.17 AM.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.58.04 AM.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 12.00.06 PM.png")); // NOI18N
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        goal.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        goal.setForeground(new java.awt.Color(0, 204, 102));
        goal.setText("sfhbskhf");
        jPanel2.add(goal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, 20));

        area.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        area.setForeground(new java.awt.Color(0, 204, 102));
        area.setText("uttar pradesh gujrat chittasghar kanpur");
        jPanel2.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 360, 30));

        product.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        product.setForeground(new java.awt.Color(0, 204, 102));
        product.setText(" b fsv kdf");
        jPanel2.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 230, 30));

        jLabel28.setForeground(new java.awt.Color(102, 102, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-05 at 8.48.53 PM.png")); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-05 at 8.48.53 PM.png")); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 370, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-05 at 8.48.53 PM.png")); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 290, 30));

        preview.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-02 at 3.05.00 PM.png")); // NOI18N
        jPanel2.add(preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 420, 200));

        jLabel19.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-02 at 3.07.13 PM.png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, -1, 210));

        jLabel7.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Logo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 100, -1));

        jPanel8.setBackground(new java.awt.Color(212, 211, 211));
        jPanel8.setForeground(new java.awt.Color(153, 153, 153));

        jLabel21.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 4.12.15 PM.png")); // NOI18N

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel22.setText("2018 AdLabs | ");

        privacy1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        privacy1.setForeground(new java.awt.Color(0, 153, 255));
        privacy1.setText("Privacy Policy");
        privacy1.setBorderPainted(false);
        privacy1.setContentAreaFilled(false);
        privacy1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        privacy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(privacy1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 680, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(privacy1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 960, 20));

        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("To:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 30, 30));

        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("From:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 30));

        LogOut1.setBackground(new java.awt.Color(255, 0, 51));
        LogOut1.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.26.05 PM.png")); // NOI18N
        LogOut1.setText("LOG OUT");
        LogOut1.setBorderPainted(false);
        LogOut1.setContentAreaFilled(false);
        LogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 150, 54));

        current_id.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        current_id.setForeground(new java.awt.Color(0, 204, 102));
        current_id.setText("Ad Id : 240201997 ( Active )");
        jPanel2.add(current_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 450, 50));

        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 220, 190));

        img.setForeground(new java.awt.Color(255, 255, 255));
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        jPanel2.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 220, 190));

        jLabel9.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, -1));

        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 100, 40));

        Stop.setAutoscrolls(true);
        Stop.setBorderPainted(false);
        Stop.setContentAreaFilled(false);
        Stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });
        jPanel2.add(Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 100, 40));

        jLabel10.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Image");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 4.53.13 PM.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 561, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 5.03.48 PM.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 559, 110, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logout Successfully ");
        this.dispose();
        front nf = new front();
        nf.setVisible(rootPaneCheckingEnabled);
    }                                       

    private void privacy1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        privacy.main(info);
    }                                        

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        this.dispose();
        Analytics.main(info);
    }                                    

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        try{
            make_connection();
            int id = Integer.parseInt(info[2]);
            make_connection();
            String q = "SELECT * FROM StopEmailID WHERE ID = ?";
            pst = (PreparedStatement) con.prepareStatement(q);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            if( !rs.next() ){
                q = "INSERT INTO StopEmailID VALUES ( ?, ? )";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, info[1]);
                pst.setInt(2, id);
                pst.executeUpdate();
                q = "DELETE FROM EmailID WHERE AdsId = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Ad Stops");
                this.dispose();
                Analytics.main(info);
            }
            else{
                JOptionPane.showMessageDialog(null, "Ad Already Stopped");
            }
        }
        catch( NumberFormatException | SQLException e){
            System.out.println(""+e);
        }
    }                                    

    private void Home2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        this.dispose();
        runAdd.main(info);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        for( int i = 0; i < args.length; i++ ){
            info[i] = args[i];
        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AboutAd().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AboutAd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Home2;
    private javax.swing.JButton LogOut1;
    private javax.swing.JButton Stop;
    private javax.swing.JLabel URL;
    private javax.swing.JLabel area;
    private javax.swing.JButton back;
    private javax.swing.JLabel current_id;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel goal;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel preview;
    private javax.swing.JButton privacy1;
    private javax.swing.JLabel product;
    // End of variables declaration                   
}
