/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlabs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public class Analytics extends javax.swing.JFrame {

    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    public void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }

    // username, userid
    public static String info[] = new String[100];
    public String debug(int l){
        String s = "";
        for( int i = 0; i < l; i++ ){
            s += info[i];
            s += "\n";
        }
        return s;
    }
    
    /**
     * Creates new form Analytics
     */
    public Analytics() {
        initComponents();
        LogOut1.setText(info[0]);
        if( info[1] != null ){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                String sql_url = "jdbc:mysql://localhost:3306/adlabs";
                String sql_name = "root";
                String sql_pass = "light";
                con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
                stmt = con.createStatement();  
                String q = "SELECT * FROM EmailID WHERE EMAIL = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, info[1]);
                rs = pst.executeQuery();
                int flag = 0, i = 1;
                String s = "";
                while( rs.next() ){
                    s += ("    " + i + ".         "+ rs.getInt(2) + "\n");
                    i++;
                }
                if( s.length() > 0 ){
                    s = "    S.No          ID\n" + s;
                    report.setText(s);
                }
                else{
                    report.setText("\n\n\n                 No Active Ads");
                }
                q = "SELECT * FROM StopEmailID WHERE EMAIL = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, info[1]);
                rs = pst.executeQuery();
                flag = 0; i = 1;
                s = "";
                while( rs.next() ){
                    s += ("    " + i + ".         "+ rs.getInt(2) + "\n");
                    i++;
                }
                if( s.length() > 0 ){
                    s = "    S.No          ID\n" + s;
                    preport.setText(s);
                }
                else{
                    preport.setText("\n\n\n                 No Active Ads");
                }
            }
            catch( ClassNotFoundException | SQLException e ){
                System.out.println(e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Home1 = new javax.swing.JButton();
        LogOut1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        preport = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JButton();
        Analytics = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ad");

        jLabel11.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Labs");

        Home1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.57.11 PM.png")); // NOI18N
        Home1.setBorderPainted(false);
        Home1.setContentAreaFilled(false);
        Home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Home1)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        LogOut1.setBackground(new java.awt.Color(255, 0, 51));
        LogOut1.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.26.05 PM.png")); // NOI18N
        LogOut1.setText("LOG OUT");
        LogOut1.setBorderPainted(false);
        LogOut1.setContentAreaFilled(false);
        LogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 150, 54));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 12.20.51 PM.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 173, -1, 70));

        report.setEditable(false);
        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setColumns(20);
        report.setFont(new java.awt.Font("Thonburi", 0, 20)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setRows(5);
        report.setBorder(null);
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(report);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 230));

        jLabel1.setFont(new java.awt.Font("Thonburi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Previous Ads Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Thonburi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("Active Ads Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, -1));

        preport.setEditable(false);
        preport.setBackground(new java.awt.Color(0, 0, 0));
        preport.setColumns(20);
        preport.setFont(new java.awt.Font("Thonburi", 0, 20)); // NOI18N
        preport.setForeground(new java.awt.Color(255, 255, 255));
        preport.setRows(5);
        jScrollPane2.setViewportView(preport);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 380, 230));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        Dashboard.setBackground(new java.awt.Color(153, 153, 153));
        Dashboard.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(102, 102, 102));
        Dashboard.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-29 at 7.02.27 PM.png")); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        Analytics.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        Analytics.setForeground(new java.awt.Color(102, 102, 102));
        Analytics.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-29 at 7.01.00 PM.png")); // NOI18N
        Analytics.setText("Analytics");
        Analytics.setBorderPainted(false);
        Analytics.setContentAreaFilled(false);
        Analytics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Analytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsActionPerformed(evt);
            }
        });

        feedback.setBackground(new java.awt.Color(51, 51, 51));
        feedback.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        feedback.setForeground(new java.awt.Color(102, 102, 102));
        feedback.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.48.39 PM.png")); // NOI18N
        feedback.setText("Send Feedback");
        feedback.setBorderPainted(false);
        feedback.setContentAreaFilled(false);
        feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Dashboard)
                .addGap(18, 18, 18)
                .addComponent(Analytics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedback)
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Analytics)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedback))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 960, -1));

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 1, 55)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 102));
        jLabel9.setText("Analytics");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        view.setBorderPainted(false);
        view.setContentAreaFilled(false);
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 549, 90, 40));

        ID.setBackground(new java.awt.Color(0, 0, 0));
        ID.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setBorder(null);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 12.23.22 PM.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 1.09.43 PM.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 560, 110, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText("Enter Ad Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 560, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logout Successfully ");
        this.dispose();
        front nf = new front();
        nf.setVisible(rootPaneCheckingEnabled);
    }                                       

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dispose();
        adlabs.Dashboard.main(info);
    }                                         

    private void AnalyticsActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dispose();
        adlabs.Analytics.main(info);
    }                                         

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        if( ID.getText().length() == 0 ){
            JOptionPane.showMessageDialog(null, "enter valid id");
        }
        else{
            try {
                int id = Integer.parseInt(ID.getText());
                make_connection();
                String q = "SELECT * FROM ActiveAds WHERE ID = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setInt(1, id);
                rs = pst.executeQuery();
                if( rs.next() ){
                    info[2] = ID.getText();
                    System.out.println(""+info[2]);
                    AboutAd.main(info);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "enter valid id");
                }
            }
            catch( SQLException e ){
                System.out.println(""+e);
            }
        }
    }                                    

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        this.dispose();
        runAdd.main(info);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        for( int i = 0; i < args.length; i++ ){
            info[i] = args[i];
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Analytics;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Home1;
    private javax.swing.JTextField ID;
    private javax.swing.JButton LogOut1;
    private javax.swing.JButton feedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea preport;
    private javax.swing.JTextArea report;
    private javax.swing.JButton view;
    // End of variables declaration                   
}
