/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlabs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public class Dashboard extends javax.swing.JFrame {
    
    // DB connection
    //**********************************************************************************************
    
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    
    public void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }

    /**
     * Creates new form Dashboard
     */
    
    // username, userid
    public static String info[] = new String[100];
    public String debug(int l){
        String s = "";
        for( int i = 0; i < l; i++ ){
            s += info[i];
            s += "\n";
        }
        return s;
    }
    
    public Dashboard() {
        initComponents();
        LogOut1.setText(info[0]);
        if( info[1] != null ){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                String sql_url = "jdbc:mysql://localhost:3306/adlabs";
                String sql_name = "root";
                String sql_pass = "light";
                con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
                stmt = con.createStatement();  
                String q = "SELECT * FROM UserInfo WHERE EMAIL = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, info[1]);
                rs = pst.executeQuery();
                System.out.println(""+info[1]);
                while( rs.next() ){
                    System.out.println(""+rs.getString(1)+" :P");
                    name.setText(rs.getString(1) + " " + rs.getString(2));
                    Email.setText(rs.getString(3));
                }
                q = "SELECT * FROM EmailID WHERE EMAIL = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, info[1]);
                rs = pst.executeQuery();
                int cnt = 0;
                while( rs.next() ){
                    cnt++;
                }
                Aads.setText(""+cnt);
                
                q = "SELECT * FROM StopEmailID WHERE EMAIL = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, info[1]);
                rs = pst.executeQuery();
                cnt = 0;
                while( rs.next() ){
                    cnt++;
                }
                Sads.setText(""+cnt);
            }
            catch( ClassNotFoundException | SQLException e ){
                System.out.println(e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Home1 = new javax.swing.JButton();
        LogOut1 = new javax.swing.JButton();
        Rpassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Sads = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        Aads = new javax.swing.JLabel();
        ads = new javax.swing.JButton();
        change = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JButton();
        Analytics = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ad");

        jLabel11.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Labs");

        Home1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.57.11 PM.png")); // NOI18N
        Home1.setBorderPainted(false);
        Home1.setContentAreaFilled(false);
        Home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Home1)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        LogOut1.setBackground(new java.awt.Color(255, 0, 51));
        LogOut1.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.26.05 PM.png")); // NOI18N
        LogOut1.setText("LOG OUT");
        LogOut1.setBorderPainted(false);
        LogOut1.setContentAreaFilled(false);
        LogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 150, 54));

        Rpassword.setBackground(new java.awt.Color(0, 0, 0));
        Rpassword.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Rpassword.setForeground(new java.awt.Color(255, 255, 255));
        Rpassword.setBorder(null);
        Rpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Rpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 160, 30));

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 160, 30));

        jLabel1.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("ReEnter Password : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 180, -1));

        Sads.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        Sads.setForeground(new java.awt.Color(255, 255, 255));
        Sads.setText("0");
        jPanel1.add(Sads, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 80, 30));

        jLabel3.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Name : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 80, -1));

        jLabel4.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("  Your Previous Ads :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 8.31.43 PM.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 8.31.43 PM.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 40));

        jLabel7.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("New Password : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, -1));

        jLabel8.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText(" Your Active Ads :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 160, 30));

        name.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("..");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 360, 30));

        Aads.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        Aads.setForeground(new java.awt.Color(255, 255, 255));
        Aads.setText("1");
        jPanel1.add(Aads, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 60, 30));

        ads.setFont(new java.awt.Font("Thonburi", 0, 20)); // NOI18N
        ads.setForeground(new java.awt.Color(88, 160, 233));
        ads.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-12 at 12.02.54 AM.png")); // NOI18N
        ads.setText("Ads Insights");
        ads.setBorderPainted(false);
        ads.setContentAreaFilled(false);
        ads.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adsActionPerformed(evt);
            }
        });
        jPanel1.add(ads, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 190, 40));

        change.setFont(new java.awt.Font("Thonburi", 0, 13)); // NOI18N
        change.setForeground(new java.awt.Color(66, 156, 238));
        change.setText("change");
        change.setBorderPainted(false);
        change.setContentAreaFilled(false);
        change.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 90, 40));

        jLabel13.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Email Id :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 90, -1));

        Email.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("...");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 390, 30));

        delete.setFont(new java.awt.Font("Thonburi", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 0, 0));
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 210, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 11.18.56 PM.png")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 300, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-12 at 12.09.35 AM.png")); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        Dashboard.setBackground(new java.awt.Color(153, 153, 153));
        Dashboard.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(102, 102, 102));
        Dashboard.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-29 at 7.02.27 PM.png")); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        Analytics.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        Analytics.setForeground(new java.awt.Color(102, 102, 102));
        Analytics.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-29 at 7.01.00 PM.png")); // NOI18N
        Analytics.setText("Analytics");
        Analytics.setBorderPainted(false);
        Analytics.setContentAreaFilled(false);
        Analytics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Analytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsActionPerformed(evt);
            }
        });

        feedback.setBackground(new java.awt.Color(51, 51, 51));
        feedback.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        feedback.setForeground(new java.awt.Color(102, 102, 102));
        feedback.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.48.39 PM.png")); // NOI18N
        feedback.setText("Send Feedback");
        feedback.setBorderPainted(false);
        feedback.setContentAreaFilled(false);
        feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Dashboard)
                .addGap(18, 18, 18)
                .addComponent(Analytics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedback)
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Analytics)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedback))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 960, -1));

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 1, 55)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Dashboard");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logout Successfully ");
        this.dispose();
        front nf = new front();
        nf.setVisible(rootPaneCheckingEnabled);
    }                                       

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        char[] Pass = password.getPassword();
        String p = String.copyValueOf(Pass);
        Pass = Rpassword.getPassword();
        String rp = String.copyValueOf(Pass);
        if( p.length() != 0 && p.equals(rp) ){
            try{
                String q = "UPDATE UserInfo SET Password = ? WHERE EMAIL = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setString(1, p);
                pst.setString(2, info[1]);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Password Changed");
            }
            catch(SQLException e){
                System.out.println(e+"");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Password not match");
        }
    }                                      

    private void adsActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        adlabs.Analytics.main(info);
        this.dispose();
    }                                   

    private void RpasswordActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dispose();
        adlabs.Dashboard.main(info);
    }                                         

    private void AnalyticsActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dispose();
        adlabs.Analytics.main(info);
    }                                         

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        this.dispose();
        runAdd.main(info);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        for( int i = 0; i < args.length; i++ ){
            info[i] = args[i];
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Aads;
    private javax.swing.JButton Analytics;
    private javax.swing.JButton Dashboard;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Home1;
    private javax.swing.JButton LogOut1;
    private javax.swing.JPasswordField Rpassword;
    private javax.swing.JLabel Sads;
    private javax.swing.JButton ads;
    private javax.swing.JButton change;
    private javax.swing.JButton delete;
    private javax.swing.JButton feedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField password;
    // End of variables declaration                   
}
