/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlabs;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public class Forget extends javax.swing.JFrame {

    /**
     * Creates new form Forget
     */
    public Forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Left = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Labs");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 80, -1));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 40, -1));

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("KufiStandardGK", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.48.48 AM.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.47.59 AM.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.33.11 AM.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 380, -1));

        Next.setBorderPainted(false);
        Next.setContentAreaFilled(false);
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        Next.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NextKeyReleased(evt);
            }
        });
        jPanel1.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 90, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 9.03.09 AM.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        Left.setFont(new java.awt.Font("KufiStandardGK", 0, 18)); // NOI18N
        Left.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 20));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    // DB connection
    //**********************************************************************************************
    
    java.sql.PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    
    void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }
    
    //**********************************************************************************************
    private void NextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        try{
            
            String EMail = Email.getText();
            make_connection();
            String query = "SELECT * FROM UserInfo WHERE Email = ?";
            pst = (PreparedStatement) con.prepareStatement(query);
            pst.setString(1, EMail);
            rs = pst.executeQuery();
            if( rs.next() ){
                String p = rs.getString(4);
                
                String to ,sub, msg;
                msg = p;
                to = EMail;
                Thread thread = new Thread(new MailSender(to, msg));// parallel programming
                thread.start();
                JOptionPane.showMessageDialog(null,"Your password sent to your email id");
                this.dispose();
                login l = new login();
                l.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Incorrect Email Id :(");
            }
        }catch( SQLException e ){
            System.out.println(""+e);
        }
    }                                    

    private void NextKeyReleased(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        
    }                                

    private void NextKeyPressed(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
        
    }                               

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Left;
    private javax.swing.JButton Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
