/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlabs;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Forget = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.37.14 AM.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setFont(new java.awt.Font("KufiStandardGK", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 330, 20));

        jLabel2.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Labs");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 90, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.34.27 AM.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 390, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.48.48 AM.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 50, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.47.59 AM.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 20));

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("KufiStandardGK", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 380, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 8.33.11 AM.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 380, -1));

        Forget.setFont(new java.awt.Font("Lao Sangam MN", 0, 14)); // NOI18N
        Forget.setForeground(new java.awt.Color(88, 141, 229));
        Forget.setText("Forget Password?");
        Forget.setBorderPainted(false);
        Forget.setContentAreaFilled(false);
        Forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetActionPerformed(evt);
            }
        });
        jPanel1.add(Forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, -1));

        jLabel7.setFont(new java.awt.Font("KufiStandardGK", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("to continue to AdLabs");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        Login.setBorderPainted(false);
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 90, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 9.03.09 AM.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    // DB connection
    //**********************************************************************************************
    
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    
    void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }
    
    //**********************************************************************************************
    
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        try{
            String EMail = Email.getText();
            char a[] = Password.getPassword();
            String pass = String.copyValueOf(a);
            if( pass.length() == 0 ){
                 JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
            }
            else if( EMail.length() == 0 ){
                 JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
            }
            else{
                make_connection();
                String query = "SELECT * FROM UserInfo WHERE Email = ? and Password = ?";
                pst = (PreparedStatement) con.prepareStatement(query);
                pst.setString(1,EMail);
                pst.setString(2, pass);
                rs = pst.executeQuery();
                if( rs.next() ){
                    String info[] = new String[2];
                    info[0] = rs.getString("FirstName");
                    info[1] = rs.getString("Email");
                    this.dispose();
                    runAdd.main(info);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Incorrect Email or Password");
                    
                }
            }
        }
        catch(HeadlessException | SQLException e){
            System.out.println(""+e);
        }
    }                                     

    private void ForgetActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Forget Fp = new Forget();
        Fp.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Email;
    private javax.swing.JButton Forget;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
