/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adlabs;

import java.util.Random; 
import java.sql.Date; 
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public class SevenRunAdd extends javax.swing.JFrame {

    /** Creates new form SevenRunAdd */
    
    // DB connection
    //**********************************************************************************************
    
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    
    public void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }
    
    //**********************************************************************************************

    
    // username userid goal 4_states language category h1 h2 desc web img logo sel sdate edate
    
    public static String info[] = new String[100];
    public static String info1[] = new String[100];
    public String debug(int l){
        String s = "";
        for( int i = 0; i < l; i++ ){
            s += info[i];
            s += "\n";
        }
        return s;
    }
    
    public SevenRunAdd() {
        initComponents();
        if( info[0] != null ){
            LogOut1.setText(info[0]);
            int c = 0;
            String s = info[15];
            System.out.println(":P "+s);
            for( int i = 0; i < s.length(); i++ ){
               c = c * 10 + (s.charAt(i) - '0' );
            }
            views.setText(""+((c*2)+13)+" - "+((c*3)+11)+" views");
            clicks.setText(""+((c)-11)/2+" - "+((c*2)-19)/3+" clicks");
            String text;
            if( "Call Goal".equals(info[2]) ){
                text = "Call your business";
            }
            else{
                text = "Take an action on your website";
            }
            goal.setText(text);
            area.setText(info[3] + "       " + info[4]);
            area2.setText(info[5] + "       " + info[6]);
            product.setText(info[8]);
            int rs = Integer.parseInt(info[15]);
            Budget.setText("Rs. "+rs+".00");
            Budget1.setText("Rs. "+rs*30+".00");
            headline.setText(info[9] + " | " + info[10]);
            URL.setText(info[11]);
            desc.setText(info[12]);
            String d = info[18] + "-" + info[17] + "-" + info[16];
            date.setText(d);
            d = info[21] + "-" + info[20] + "-" + info[19];
            date1.setText(d);
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Home1 = new javax.swing.JButton();
        headline = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        clicks = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        views = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        URL = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        LogOut1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        goal = new javax.swing.JLabel();
        area = new javax.swing.JLabel();
        area2 = new javax.swing.JLabel();
        product = new javax.swing.JLabel();
        Budget = new javax.swing.JLabel();
        Budget1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        preview = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        privacy1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ad");

        jLabel11.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Labs");

        Home1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.57.11 PM.png")); // NOI18N
        Home1.setBorderPainted(false);
        Home1.setContentAreaFilled(false);
        Home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Home1)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 819, -1));

        headline.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        headline.setForeground(new java.awt.Color(153, 153, 255));
        headline.setText("Headline1 | Headline2");
        jPanel1.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 390, 30));

        desc.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 153, 153));
        desc.setText("Description");
        jPanel1.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 380, 30));

        clicks.setForeground(new java.awt.Color(88, 160, 233));
        clicks.setText("vjhbsfhd");
        jPanel1.add(clicks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, 20));

        date1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        date1.setForeground(new java.awt.Color(88, 160, 233));
        date1.setText("2018-9-2");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 130, 30));

        date.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(88, 160, 233));
        date.setText("2-9-2018");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 130, 30));

        views.setForeground(new java.awt.Color(88, 160, 233));
        views.setText("bkhbfdkh");
        jPanel1.add(views, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 12.01.22 PM.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 190, 50));

        URL.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        URL.setForeground(new java.awt.Color(122, 191, 130));
        URL.setText("website URL");
        jPanel1.add(URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 350, 50));

        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 130, 40));

        LogOut1.setBackground(new java.awt.Color(255, 0, 51));
        LogOut1.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 3.26.05 PM.png")); // NOI18N
        LogOut1.setText("LOG OUT");
        LogOut1.setBorderPainted(false);
        LogOut1.setContentAreaFilled(false);
        LogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 0, 150, 54));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.50.01 AM.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 140, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.51.04 AM.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.51.57 AM.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.55.17 AM.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 330, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.58.04 AM.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 440, 180, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-11 at 10.56.32 PM.png")); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 572, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 11.57.34 AM.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-09 at 12.00.06 PM.png")); // NOI18N
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        goal.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        goal.setForeground(new java.awt.Color(88, 160, 233));
        goal.setText("sfhbskhf");
        jPanel1.add(goal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, 20));

        area.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        area.setForeground(new java.awt.Color(88, 160, 233));
        area.setText("fsfhmdk");
        jPanel1.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 250, 30));

        area2.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        area2.setForeground(new java.awt.Color(88, 160, 233));
        area2.setText("sfhbhf");
        jPanel1.add(area2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 250, 30));

        product.setFont(new java.awt.Font("Baghdad", 1, 13)); // NOI18N
        product.setForeground(new java.awt.Color(88, 160, 233));
        product.setText(" b fsv kdf");
        jPanel1.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 230, 30));

        Budget.setFont(new java.awt.Font("Baghdad", 1, 36)); // NOI18N
        Budget.setForeground(new java.awt.Color(88, 160, 233));
        Budget.setText("Rs. 1111.00");
        jPanel1.add(Budget, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 220, 50));

        Budget1.setFont(new java.awt.Font("Baghdad", 1, 36)); // NOI18N
        Budget1.setForeground(new java.awt.Color(88, 160, 233));
        Budget1.setText("Rs. 311111.00");
        jPanel1.add(Budget1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 260, 60));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("daily");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, 30));

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("average");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, 40));

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("monthly");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 80, 30));

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("maximum");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 90, 40));

        jLabel28.setForeground(new java.awt.Color(102, 102, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-05 at 8.48.53 PM.png")); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-05 at 8.48.53 PM.png")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 370, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-05 at 8.48.53 PM.png")); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 290, 30));

        preview.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-02 at 3.05.00 PM.png")); // NOI18N
        jPanel1.add(preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 420, 200));

        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-02 at 3.07.13 PM.png")); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, -1, 210));

        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 90, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-01 at 7.18.33 PM.png")); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jLabel7.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 100, -1));

        jPanel7.setBackground(new java.awt.Color(212, 211, 211));
        jPanel7.setForeground(new java.awt.Color(153, 153, 153));

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-10-30 at 4.12.15 PM.png")); // NOI18N

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel21.setText("2018 AdLabs | ");

        privacy1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        privacy1.setForeground(new java.awt.Color(0, 153, 255));
        privacy1.setText("Privacy Policy");
        privacy1.setBorderPainted(false);
        privacy1.setContentAreaFilled(false);
        privacy1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        privacy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(privacy1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 680, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(privacy1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 960, 20));

        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("To:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 30, 30));

        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("From:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logout Successfully ");
        this.dispose();
        front nf = new front();
        nf.setVisible(rootPaneCheckingEnabled);
    }                                       

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        try{
            Random rand = new Random(); 
            for( int i = 1; i < 22; i++ ){
                info1[i-1] = info[i];
            }
            make_connection();
            int ID = 5;
            for( int i = 0; i < 1000; i++ ){
                ID = rand.nextInt(1000); 
                ID += 24021997;
                String q = "SELECT * FROM ActiveAds WHERE ID = ?";
                pst = (PreparedStatement) con.prepareStatement(q);
                pst.setInt(1, ID);
                rs = pst.executeQuery();
                if( !rs.next() ){
                    q = "INSERT INTO EmailID VALUES ( ?, ? )";
                    pst = (PreparedStatement) con.prepareStatement(q);
                    pst.setString(1, info[1]);
                    pst.setInt(2, ID);
                    pst.executeUpdate();
                    break;
                }
            }
            String query = "INSERT INTO ActiveAds VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";
            pst = (PreparedStatement) con.prepareStatement(query);
            
            // username userid goal 4_states language category h1 h2 desc web img logo sel sdate edate
                                                                                             pst.setInt(13, ID);
            String GOAL = info1[1];                                                          pst.setString(1, GOAL);
            String STATES = info1[5] + " " + info1[2] + " " + info1[3] + " " + info1[4];     pst.setString(2, STATES);
            String LAN = info1[6];                                                           pst.setString(3, LAN);
            String CAT = info1[7];                                                           pst.setString(4, CAT);
            String HEAD = info1[8] + " | " + info1[9];                                       pst.setString(5, HEAD);
            String DES = info1[10];                                                          pst.setString(6, DES);
            String WEB = info1[11];                                                          pst.setString(7, WEB);
            String IMG = info1[12];    
            InputStream img = new FileInputStream(new File(IMG));                            pst.setBlob(8, img);
            String LOGO = info1[13];    
            InputStream logo = new FileInputStream(new File(LOGO));                          pst.setBlob(9, logo);
            int COST = Integer.parseInt(info1[14]);                                          pst.setInt(10, COST);
            String SDATE = "" + info1[15] + "-" + info1[16] + "-" + info1[17];                                                                       
            Date start = Date.valueOf(SDATE);                                                pst.setDate(11,start);                                                                      
            String EDATE = "" + info1[18] + "-" + info1[19] + "-" + info1[20]; 
            Date end = Date.valueOf(EDATE);                                                  pst.setDate(12,end);                                      
            System.out.println(""+start + " " + end);                                                                                                       
                                                                                             pst.executeUpdate();
            JOptionPane.showMessageDialog(null, debug(22));
            Run.main(info);
            this.dispose();
        }
        catch( HeadlessException | SQLException e ){
            System.out.println(e);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SevenRunAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                    

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        this.dispose();
        SixRunAdd.main(info);
    }                                    

    private void privacy1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        privacy.main(info);
    }                                        

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        this.dispose();
        runAdd.main(info);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        for( int i = 0; i < args.length; i++ ){
            info[i] = args[i];
            info1[i] = info[i];
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SevenRunAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SevenRunAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SevenRunAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SevenRunAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SevenRunAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Budget;
    private javax.swing.JLabel Budget1;
    private javax.swing.JButton Home1;
    private javax.swing.JButton LogOut1;
    private javax.swing.JLabel URL;
    private javax.swing.JLabel area;
    private javax.swing.JLabel area2;
    private javax.swing.JButton back;
    private javax.swing.JLabel clicks;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel goal;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton next;
    private javax.swing.JLabel preview;
    private javax.swing.JButton privacy1;
    private javax.swing.JLabel product;
    private javax.swing.JLabel views;
    // End of variables declaration                   

}
