/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adlabs;

import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mohitrai
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Cpassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstName.setBackground(new java.awt.Color(0, 0, 0));
        FirstName.setFont(new java.awt.Font("KufiStandardGK", 0, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setBorder(null);
        FirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 30));

        LastName.setBackground(new java.awt.Color(0, 0, 0));
        LastName.setFont(new java.awt.Font("KufiStandardGK", 0, 15)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setBorder(null);
        jPanel1.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, 30));

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("KufiStandardGK", 0, 15)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 360, 30));

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, 20));

        Cpassword.setBackground(new java.awt.Color(0, 0, 0));
        Cpassword.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        Cpassword.setForeground(new java.awt.Color(255, 255, 255));
        Cpassword.setBorder(null);
        Cpassword.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 150, 20));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, -1));

        jLabel2.setFont(new java.awt.Font("Noteworthy", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Labs");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.00.04 AM.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 63, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.00.39 AM.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 60, 110, 50));

        jLabel7.setFont(new java.awt.Font("KufiStandardGK", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("to continue to AdLabs");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.04.39 AM.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 170, 200, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.04.25 AM.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.06.03 AM.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.07.53 AM.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 330, 210, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.07.36 AM.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 324, -1, 70));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Use 8 or more characters with a mix of letters, numbers & symbols ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));

        Login.setBorderPainted(false);
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 90, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 9.03.09 AM.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/mohitrai/Desktop/Screenshot 2018-11-06 at 11.27.01 AM.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("KufiStandardGK", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("All of AdLabs");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("KufiStandardGK", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("working for you.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    // DB connection
    //**********************************************************************************************
    
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con;
    
    void make_connection(){ // for making the connection with database
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql_url = "jdbc:mysql://localhost:3306/adlabs";
            String sql_name = "root";
            String sql_pass = "light";
            con = (Connection) DriverManager.getConnection(sql_url, sql_name, sql_pass);
            stmt = con.createStatement();  
        }
        catch( ClassNotFoundException | SQLException e ){
            System.out.println(e);
        }
    }
    
    //**********************************************************************************************
    
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         try{
            String Fname = FirstName.getText();
            String Lname = LastName.getText();
            String EMail = Email.getText();
            char[] Pa = Password.getPassword();
            char[] RePa = Cpassword.getPassword();
            String Pass = String.copyValueOf(Pa);
            String Repass = String.copyValueOf(RePa);
            if( Fname.length() == 0 || Lname.length() == 0 || EMail.length() == 0 ){
                JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
            }
            else if( Pass.length() < 8 ){
                JOptionPane.showMessageDialog(null, "Password must be of atleast 8 lenght");
            }
            else if( !Pass.equals(Repass) ){
               JOptionPane.showMessageDialog(null, "Password Mismatch");
            }
            else{
                make_connection();
                String c_query = "SELECT * FROM UserInfo WHERE Email = ?";
                pst = (PreparedStatement) con.prepareStatement(c_query);
                pst.setString(1,EMail);
                rs = pst.executeQuery();
                if( !rs.next() ){
                     String query = "INSERT INTO UserInfo VALUES( ?, ?, ?, ?)";
                       pst = (PreparedStatement) con.prepareStatement(query);
                       pst.setString(1, Fname);
                       pst.setString(2, Lname);
                       pst.setString(3, EMail);
                       pst.setString(4, Pass);
                       pst.executeUpdate();
                       JOptionPane.showMessageDialog(null, "Time to run some Ads.");
                       this.dispose();
                       login open_login = new login();
                       open_login.setVisible(rootPaneCheckingEnabled);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Email already used"); 
                }  
            }
        }
        catch( HeadlessException | SQLException e ){
            System.out.println(e);
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPasswordField Cpassword;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
